export const departamentosCatamarca = [
  "Ambato",
  "Ancasti",
  "Andalgala",
  "Antofagasta de la Sierra",
  "Belen",
  "Capayan",
  "Capital",
  "El Alto",
  "Fray Mamerto Esquiu",
  "La Paz",
  "Paclin",
  "Poman",
  "Santa Maria",
  "Santa Rosa",
  "Tinogasta",
  "Valle Viejo",
];
